<?php /* Smarty version 2.6.26, created on 2018-06-14 09:57:00
         compiled from common/cycle.tpl */ ?>
<?php $this->assign('cr_display_all', false); ?><?php if ($this->_tpl_vars['allprices']): ?><?php $this->assign('cr_display_all', true); ?><?php endif; ?><?php if ($this->_tpl_vars['product']['paytype'] == 'Free'): ?><?php if ($this->_tpl_vars['cr_display_all'] || $this->_tpl_vars['wrap']): ?><span class="product-cycle cycle-free"><?php endif; ?><?php echo $this->_tpl_vars['lang']['Free']; ?>
<?php if ($this->_tpl_vars['cr_display_all'] || $this->_tpl_vars['wrap']): ?></span><?php endif; ?><?php elseif ($this->_tpl_vars['product']['paytype'] == 'Once'): ?><?php if ($this->_tpl_vars['cr_display_all'] || $this->_tpl_vars['wrap']): ?><span class="product-cycle cycle-once"><?php endif; ?><?php echo $this->_tpl_vars['lang']['once']; ?>
<?php if ($this->_tpl_vars['cr_display_all'] || $this->_tpl_vars['wrap']): ?></span><?php endif; ?><?php else: ?><?php if ($this->_tpl_vars['cr_display_all'] && $this->_tpl_vars['wrap'] == 'select'): ?><select name="<?php echo $this->_tpl_vars['allprices']; ?>
" ><?php endif; ?><?php $_from = $this->_tpl_vars['product']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['p_cycle'] => $this->_tpl_vars['p_price']):
?><?php if ($this->_tpl_vars['p_cycle'] == 'd' || $this->_tpl_vars['p_cycle'] == 'w' || $this->_tpl_vars['p_cycle'] == 'm' || $this->_tpl_vars['p_cycle'] == 'q' || $this->_tpl_vars['p_cycle'] == 's' || $this->_tpl_vars['p_cycle'] == 'a' || $this->_tpl_vars['p_cycle'] == 'b' || $this->_tpl_vars['p_cycle'] == 't' || $this->_tpl_vars['p_cycle'] == 'p4' || $this->_tpl_vars['p_cycle'] == 'p5'): ?><?php if ($this->_tpl_vars['p_price'] > 0): ?><?php if ($this->_tpl_vars['cr_display_all'] && $this->_tpl_vars['wrap'] == 'select'): ?><option value="<?php echo $this->_tpl_vars['p_cycle']; ?>
" <?php if ($this->_tpl_vars['cycle'] == $this->_tpl_vars['p_cycle']): ?>selected="selected"<?php endif; ?>><?php elseif ($this->_tpl_vars['cr_display_all'] || $this->_tpl_vars['wrap']): ?><span class="product-cycle cycle-<?php echo $this->_tpl_vars['p_cycle']; ?>
"><?php endif; ?><?php echo $this->_tpl_vars['lang'][$this->_tpl_vars['p_cycle']]; ?>
<?php if ($this->_tpl_vars['cr_display_all'] && $this->_tpl_vars['wrap'] == 'select'): ?></option><?php elseif ($this->_tpl_vars['cr_display_all'] || $this->_tpl_vars['wrap']): ?></span><?php endif; ?><?php if (! $this->_tpl_vars['cr_display_all']): ?><?php break; ?><?php endif; ?><?php endif; ?><?php endif; ?><?php endforeach; endif; unset($_from); ?><?php if ($this->_tpl_vars['cr_display_all'] && $this->_tpl_vars['wrap'] == 'select'): ?></select><?php endif; ?><?php endif; ?>